<a href="https://colab.research.google.com/github/PyBlin/Study/blob/main/AI_Class1/Day14.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy

In [1]:
# ! : 외부 명령 실행
# pip : 파이썬 패키지 관리 명령
# list : pip 명령에서 사용하여 매개변수, 설치된 패키지 목록 확인

# pip install numpy ==> pip 매개변수 패키지

!pip list

Package                       Version
----------------------------- --------------
absl-py                       0.12.0
alabaster                     0.7.12
albumentations                0.1.12
altair                        4.1.0
appdirs                       1.4.4
argcomplete                   1.12.3
argon2-cffi                   20.1.0
arviz                         0.11.2
astor                         0.8.1
astropy                       4.3.1
astunparse                    1.6.3
atari-py                      0.2.9
atomicwrites                  1.4.0
attrs                         21.2.0
audioread                     2.1.9
autograd                      1.3
Babel                         2.9.1
backcall                      0.2.0
beautifulsoup4                4.6.3
bleach                        4.0.0
blis                          0.4.1
bokeh                         2.3.3
Bottleneck                    1.3.2
branca                        0.4.2
bs4                           0.0.1
CacheControl

In [2]:
import numpy as np      # NumPy 임포트, 통상 alias = np

In [3]:
dir(np)
# 대문자 : 변수(Symbolic Constant)
# 소문자 : 함수

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__file__',
 '__getattr__',
 '__git_revision__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_

In [4]:
np.__version__

'1.19.5'

In [5]:
def asprint(arr):
    # NumPy ndarray 객체 속성 (attribute)
    # arr 인수 : ndarray 객체 (array)

    # shape : array 구조
    # ndim : array 차원
    # dtype : array 자료형

    print(f'type : {type(arr)}')
    print(f'shape : {arr.shape}\tdimension = {arr.ndim}')
    print(f'dtype : {arr.dtype}', '\n')
    print(f"Array's data : \n{arr}")

## NumPy 배열 생성

In [6]:
# 파이썬 1차원 list로 NumPy 배열 생성
l = [1, 2, 3]
a = np.array(l)

In [7]:
asprint(a)

type : <class 'numpy.ndarray'>
shape : (3,)	dimension = 1
dtype : int64 

Array's data : 
[1 2 3]


In [8]:
# 파이썬 2차원 list로 NumPy 배열 생성
l = [[1, 2, 3], [4, 5, 6]]
a = np.array(l)

In [9]:
asprint(a)

type : <class 'numpy.ndarray'>
shape : (2, 3)	dimension = 2
dtype : int64 

Array's data : 
[[1 2 3]
 [4 5 6]]


In [10]:
a = np.array([[[1, 2, 3],
      [4, 5, 6]],
     [[3, 2, 1],
      [6, 5, 4]]], dtype = float)

In [11]:
asprint(a)

type : <class 'numpy.ndarray'>
shape : (2, 2, 3)	dimension = 3
dtype : float64 

Array's data : 
[[[1. 2. 3.]
  [4. 5. 6.]]

 [[3. 2. 1.]
  [6. 5. 4.]]]


## NumPy 배열 생성 및 초기화

In [12]:
a = np.zeros((3, 4))    # 0으로 초기화된 배열 생성
asprint(a)

type : <class 'numpy.ndarray'>
shape : (3, 4)	dimension = 2
dtype : float64 

Array's data : 
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [13]:
a = np.ones((3, 4))     # 1로 초기화된 배열 생성
asprint(a)

type : <class 'numpy.ndarray'>
shape : (3, 4)	dimension = 2
dtype : float64 

Array's data : 
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [14]:
a = np.full((3, 4), 7)  # 임의의 값으로 초기화된 배열 생성
asprint(a)

type : <class 'numpy.ndarray'>
shape : (3, 4)	dimension = 2
dtype : int64 

Array's data : 
[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


In [15]:
a = np.eye(4)           # (N, N) 구조의 단위 행렬 생성
asprint(a)

type : <class 'numpy.ndarray'>
shape : (4, 4)	dimension = 2
dtype : float64 

Array's data : 
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [16]:
a = np.empty((3, 4))    # 초기화되지 않는 (쓰레기값) 배열 생성
asprint(a)

type : <class 'numpy.ndarray'>
shape : (3, 4)	dimension = 2
dtype : float64 

Array's data : 
[[3.5e-323 3.5e-323 3.5e-323 3.5e-323]
 [3.5e-323 3.5e-323 3.5e-323 3.5e-323]
 [3.5e-323 3.5e-323 3.5e-323 3.5e-323]]


In [17]:
a = np.arange(1, 9, 2)  # range()를 이용한 1차원 배열 생성
asprint(a)

type : <class 'numpy.ndarray'>
shape : (4,)	dimension = 1
dtype : int64 

Array's data : 
[1 3 5 7]


In [18]:
a = np.linspace(0, 1, 5)    # 0 ~ 1 ... 5개의 균일 간격의 값을 갖는 배열 생성
asprint(a)

type : <class 'numpy.ndarray'>
shape : (5,)	dimension = 1
dtype : float64 

Array's data : 
[0.   0.25 0.5  0.75 1.  ]


## indexing, slicing, subset

In [19]:
# reshape() : 배열 구조 변환 method

a1 = np.arange(24)                      # 1차원 배열 생성
a2 = np.arange(24).reshape((4, 6))      # 2차원 배열 생성
a3 = np.arange(24).reshape((2, 4, 3))   # 3차원 배열 생성

In [20]:
asprint(a1)

type : <class 'numpy.ndarray'>
shape : (24,)	dimension = 1
dtype : int64 

Array's data : 
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [21]:
asprint(a2)

type : <class 'numpy.ndarray'>
shape : (4, 6)	dimension = 2
dtype : int64 

Array's data : 
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [22]:
asprint(a3)

type : <class 'numpy.ndarray'>
shape : (2, 4, 3)	dimension = 3
dtype : int64 

Array's data : 
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


In [23]:
a1[5]

5

In [24]:
a1[5] = 100000
asprint(a1)

type : <class 'numpy.ndarray'>
shape : (24,)	dimension = 1
dtype : int64 

Array's data : 
[     0      1      2      3      4 100000      6      7      8      9
     10     11     12     13     14     15     16     17     18     19
     20     21     22     23]


In [25]:
a2[0, 1]

1

In [26]:
a2[0, 1] = 100000   # 파이썬 중첩 list에서는 a2[0][1]... NumPy와의 차이점
asprint(a2)

type : <class 'numpy.ndarray'>
shape : (4, 6)	dimension = 2
dtype : int64 

Array's data : 
[[     0 100000      2      3      4      5]
 [     6      7      8      9     10     11]
 [    12     13     14     15     16     17]
 [    18     19     20     21     22     23]]


In [27]:
a3[1, 0, 1]     # [면, 행, 열]

13

In [28]:
a3[1, 0, 1] = 100000
asprint(a3)

type : <class 'numpy.ndarray'>
shape : (2, 4, 3)	dimension = 3
dtype : int64 

Array's data : 
[[[     0      1      2]
  [     3      4      5]
  [     6      7      8]
  [     9     10     11]]

 [[    12 100000     14]
  [    15     16     17]
  [    18     19     20]
  [    21     22     23]]]


In [29]:
a1[0:2]

array([0, 1])

In [30]:
a2[1:3, 1:5]

array([[ 7,  8,  9, 10],
       [13, 14, 15, 16]])

In [31]:
a2[1:-1, 1:-1]      # 2차원 배열의 1행 ~ 마지막 전 행, 1열 ~ 마지막 전 열 까지

array([[ 7,  8,  9, 10],
       [13, 14, 15, 16]])

### slicing을 이용한 subset 생성

In [32]:
s_a = a2[1:3, 1:5]  # slicing을 이용한 배열. a2 배열의 subset.
asprint(s_a)

type : <class 'numpy.ndarray'>
shape : (2, 4)	dimension = 2
dtype : int64 

Array's data : 
[[ 7  8  9 10]
 [13 14 15 16]]


In [33]:
s_a[0]  # 2차원 배열의 0행

array([ 7,  8,  9, 10])

In [34]:
s_a[0, 1]

8

In [35]:
s_a[:, 1:3]     # [전체 행, 1~2 열]

array([[ 8,  9],
       [14, 15]])

In [36]:
# ndarray 객체(배열)는 slicing을 이용하여 배열 요소 일괄 변경 가능
a2[0, 1:4] = 999999
asprint(a2)

type : <class 'numpy.ndarray'>
shape : (4, 6)	dimension = 2
dtype : int64 

Array's data : 
[[     0 999999 999999 999999      4      5]
 [     6      7      8      9     10     11]
 [    12     13     14     15     16     17]
 [    18     19     20     21     22     23]]


In [37]:
# a2의 subset인 s_a의 전체 행, 1~2 열의 내용을 변경
s_a[:, 1:3] = 1000000
asprint(s_a)

type : <class 'numpy.ndarray'>
shape : (2, 4)	dimension = 2
dtype : int64 

Array's data : 
[[      7 1000000 1000000      10]
 [     13 1000000 1000000      16]]


In [38]:
asprint(a2)

type : <class 'numpy.ndarray'>
shape : (4, 6)	dimension = 2
dtype : int64 

Array's data : 
[[      0  999999  999999  999999       4       5]
 [      6       7 1000000 1000000      10      11]
 [     12      13 1000000 1000000      16      17]
 [     18      19      20      21      22      23]]


In [39]:
# reshape() method에서 -1을 행 또는 열에 사용하면 열 또는 행의 값에 따라
# 자동으로 행 또는 열의 수를 결정.
a2 = np.arange(24).reshape((-1, 6))
asprint(a2)

type : <class 'numpy.ndarray'>
shape : (4, 6)	dimension = 2
dtype : int64 

Array's data : 
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [40]:
even_arr = a2 % 2 == 0      # 각 요소를 2로 나눠라 --> easy~
asprint(even_arr)

type : <class 'numpy.ndarray'>
shape : (4, 6)	dimension = 2
dtype : bool 

Array's data : 
[[ True False  True False  True False]
 [ True False  True False  True False]
 [ True False  True False  True False]
 [ True False  True False  True False]]


In [41]:
a2[even_arr]    # boolean indexing을 적용 --> True에 해당하는 요소만 indexing

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

In [42]:
a2[a2 % 2 != 0]   # boolean indexing을 이용해서 a2의 요소 중 홀수값만 indexing

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [43]:
# boolean indexing을 파이썬으로 구현... 복잡함... NumPy가 편리함
l = [[ 0,  1,  2,  3,  4,  5],
     [ 6,  7,  8,  9, 10, 11],
     [12, 13, 14, 15, 16, 17],
     [18, 19, 20, 21, 22, 23]]

even_l = []
for row in l:
    row_l = []
    for value in row:
        if value % 2 == 0:
            row_l.append(True)
        else:
            row_l.append(False)
    even_l.append(row_l)
even_l
# 속도도 느림...
# Numpy는 C언어로 만들어서 속도가 빠름

[[True, False, True, False, True, False],
 [True, False, True, False, True, False],
 [True, False, True, False, True, False],
 [True, False, True, False, True, False]]