<a href="https://colab.research.google.com/github/PyBlin/Study/blob/main/AI_Class1/Day15.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
def asprint(arr):
    # NumPy ndarray 객체 속성 (attribute)
    # arr 인수 : ndarray 객체 (array)

    # shape : array 구조
    # ndim : array 차원
    # dtype : array 자료형

    print(f'type : {type(arr)}')
    print(f'shape : {arr.shape}\tdimension = {arr.ndim}')
    print(f'dtype : {arr.dtype}', '\n')
    print(f"Array's data : \n{arr}")

# 배열 연산

### 산술 연산

In [3]:
a = np.arange(1, 10).reshape((3, 3))
b = np.arange(9, 0, -1).reshape((3, 3))

In [4]:
asprint(a)
print()
asprint(b)

type : <class 'numpy.ndarray'>
shape : (3, 3)	dimension = 2
dtype : int64 

Array's data : 
[[1 2 3]
 [4 5 6]
 [7 8 9]]

type : <class 'numpy.ndarray'>
shape : (3, 3)	dimension = 2
dtype : int64 

Array's data : 
[[9 8 7]
 [6 5 4]
 [3 2 1]]


### 사칙연산

In [5]:
a + b

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [6]:
a - b

array([[-8, -6, -4],
       [-2,  0,  2],
       [ 4,  6,  8]])

In [7]:
a * b

array([[ 9, 16, 21],
       [24, 25, 24],
       [21, 16,  9]])

In [8]:
a / b

array([[0.11111111, 0.25      , 0.42857143],
       [0.66666667, 1.        , 1.5       ],
       [2.33333333, 4.        , 9.        ]])

In [9]:
np.add(a, b)

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [10]:
np.subtract(a, b)

array([[-8, -6, -4],
       [-2,  0,  2],
       [ 4,  6,  8]])

In [11]:
np.multiply(a, b)

array([[ 9, 16, 21],
       [24, 25, 24],
       [21, 16,  9]])

In [12]:
np.divide(a, b)

array([[0.11111111, 0.25      , 0.42857143],
       [0.66666667, 1.        , 1.5       ],
       [2.33333333, 4.        , 9.        ]])

### 산술연산

In [13]:
# 제곱근
np.sqrt(a)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [14]:
# sin
np.sin(a)

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ],
       [ 0.6569866 ,  0.98935825,  0.41211849]])

In [15]:
# cos
np.cos(a)

array([[ 0.54030231, -0.41614684, -0.9899925 ],
       [-0.65364362,  0.28366219,  0.96017029],
       [ 0.75390225, -0.14550003, -0.91113026]])

In [16]:
# tan
np.tan(a)

array([[ 1.55740772, -2.18503986, -0.14254654],
       [ 1.15782128, -3.38051501, -0.29100619],
       [ 0.87144798, -6.79971146, -0.45231566]])

In [17]:
# log
np.log(a)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [18]:
# dot product(내적)
np.dot(a, b)

array([[ 30,  24,  18],
       [ 84,  69,  54],
       [138, 114,  90]])

In [19]:
# 지수
np.exp(a)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

### 비교 연산

In [20]:
a == b

array([[False, False, False],
       [False,  True, False],
       [False, False, False]])

In [21]:
a[a == b]   # boolean indexing

array([5])

In [22]:
a > b

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

In [23]:
a[a > b]

array([6, 7, 8, 9])

In [24]:
np.array_equal(a, b)

False

In [25]:
np.array_equal(a, a)

True

### 집계 함수

In [26]:
# 합계 : sum() method, numpy.sum()
# axis = None : 전체 대상 합계 계산
a.sum(), np.sum(a)

(45, 45)

In [27]:
# axis = 0 : 행방향 합계 계산
a.sum(axis=0), np.sum(a, axis=0)

(array([12, 15, 18]), array([12, 15, 18]))

In [28]:
# axis = 1 : 열방향 합계 계산
a.sum(axis=1), np.sum(a, axis=1)

(array([ 6, 15, 24]), array([ 6, 15, 24]))

In [29]:
# 평균 : mean() method, numpy.mean()
a.mean(), np.mean(a)

(5.0, 5.0)

In [30]:
# 행방향
a.mean(axis=0), np.mean(a, axis=0)

(array([4., 5., 6.]), array([4., 5., 6.]))

In [31]:
# 열방향
a.mean(axis=1), np.mean(a, axis=1)

(array([2., 5., 8.]), array([2., 5., 8.]))

In [32]:
# 중앙값 : numpy.median()
print(np.median(a))
print(np.median(a, axis=0))
print(np.median(a, axis=1))

5.0
[4. 5. 6.]
[2. 5. 8.]


In [33]:
# 최대값 : max() method, numpy.max()
a.max(), np.max(a)

(9, 9)

In [34]:
a.max(axis=0), np.max(a, axis=0)

(array([7, 8, 9]), array([7, 8, 9]))

In [35]:
a.max(axis=1), np.max(a, axis=1)

(array([3, 6, 9]), array([3, 6, 9]))

In [36]:
# 최소값 : min() method, numpy.min()
a.min(), np.min(a)

(1, 1)

In [37]:
a.min(axis=0), np.min(a, axis=0)

(array([1, 2, 3]), array([1, 2, 3]))

In [38]:
a.min(axis=1), np.min(a, axis=1)

(array([1, 4, 7]), array([1, 4, 7]))

In [39]:
# 누적합 : cumsum() method, numpy.cumsum()
a.cumsum(), np.cumsum(a)

(array([ 1,  3,  6, 10, 15, 21, 28, 36, 45]),
 array([ 1,  3,  6, 10, 15, 21, 28, 36, 45]))

In [40]:
a.cumsum(axis=0), np.cumsum(a, axis=0)

(array([[ 1,  2,  3],
        [ 5,  7,  9],
        [12, 15, 18]]), array([[ 1,  2,  3],
        [ 5,  7,  9],
        [12, 15, 18]]))

In [41]:
a.cumsum(axis=1), np.cumsum(a, axis=1)

(array([[ 1,  3,  6],
        [ 4,  9, 15],
        [ 7, 15, 24]]), array([[ 1,  3,  6],
        [ 4,  9, 15],
        [ 7, 15, 24]]))

In [42]:
# 상관 계수(correlation coeficient) : -1 ~ 1
np.corrcoef(a)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [43]:
# 표준 편차 : std() method, numpy.std()
a.std(), np.std(a)

(2.581988897471611, 2.581988897471611)

In [44]:
a.std(axis=0), np.std(a, axis=0)

(array([2.44948974, 2.44948974, 2.44948974]),
 array([2.44948974, 2.44948974, 2.44948974]))

In [45]:
a.std(axis=1), np.std(a, axis=1)

(array([0.81649658, 0.81649658, 0.81649658]),
 array([0.81649658, 0.81649658, 0.81649658]))

In [46]:
# 분산 : var() method, numpy.var()
a.var(), np.var(a)

(6.666666666666667, 6.666666666666667)

In [47]:
a.var(axis=0), np.var(a, axis=0)

(array([6., 6., 6.]), array([6., 6., 6.]))

In [48]:
a.var(axis=1), np.var(a, axis=1)

(array([0.66666667, 0.66666667, 0.66666667]),
 array([0.66666667, 0.66666667, 0.66666667]))

In [49]:
# 최대값 인덱스 : numpy.argmax()
np.argmax(a), np.argmax(b)

(8, 0)

In [50]:
# 최소값 인덱스 : numpy.argmin()
np.argmin(a), np.argmin(b)

(0, 8)

In [51]:
# 사분위수 : numpy.percentile()

# 1사분위수 : 하위 25% 값
# 2사분위수 : 하위 50% 값 == 중앙값
# 3사분위수 : 하위 75% 값
print(f'1사분위수 : {np.percentile(a, 25)}')
print(f'2사분위수 : {np.percentile(a, 50)}')
print(f'3사분위수 : {np.percentile(a, 75)}')

1사분위수 : 3.0
2사분위수 : 5.0
3사분위수 : 7.0


In [52]:
print(f'최소값 : {a.min()}')
print(f'1사분위수 : {np.percentile(a, 25)}')
print(f'2사분위수 : {np.percentile(a, 50)}')
print(f'3사분위수 : {np.percentile(a, 75)}')
print(f'최대값 : {a.max()}')

최소값 : 1
1사분위수 : 3.0
2사분위수 : 5.0
3사분위수 : 7.0
최대값 : 9


# NumPy를 이용한 탐색적 데이터 분석(EDA 실습)

### 문제 정의 ) 미국 역대 대통령 신장 데이터를 통한 EDA

#### 0. Colab에서 파일 읽기 준비

In [53]:
from google.colab import drive
drive.mount('/drive')

Mounted at /drive


#### 1. 데이터 저장을 위한 list 생성

In [54]:
orders = []
names = []
heights = []

#### 2. 데이터 읽기

In [55]:
with open('/drive/MyDrive/Colab/AI1_Ouseoung_Lee/president_heights.csv') as f:
    lines = f.readline()    # 제목줄 읽기

    # 실제 데이터 처리
    lines = f.readline()
    while lines:
        data = lines.split(',')

        orders.append(data[0])
        names.append(data[1])
        heights.append(int(data[2][:3]))

        lines = f.readline()

#### 3. 읽어들인 데이터 확인(처음 5개, 마지막 5개 데이터 확인)

In [56]:
orders[:5], orders[len(orders) - 5:]

(['1', '2', '3', '4', '5'], ['40', '41', '42', '43', '44'])

In [57]:
names[:5], names[len(names) - 5:]

(['George Washington',
  'John Adams',
  'Thomas Jefferson',
  'James Madison',
  'James Monroe'],
 ['Ronald Reagan',
  'George H. W. Bush',
  'Bill Clinton',
  'George W. Bush',
  'Barack Obama'])

In [58]:
heights[:5], heights[len(heights) - 5:]

([189, 170, 189, 163, 183], [185, 188, 188, 182, 185])

#### 4. NumPy 배열로 변환

In [59]:
order_array = np.array(orders)
name_array = np.array(names)
height_array = np.array(heights)

In [60]:
asprint(order_array)

type : <class 'numpy.ndarray'>
shape : (42,)	dimension = 1
dtype : <U2 

Array's data : 
['1' '2' '3' '4' '5' '6' '7' '8' '9' '10' '11' '12' '13' '14' '15' '16'
 '17' '18' '19' '20' '21' '23' '25' '26' '27' '28' '29' '30' '31' '32'
 '33' '34' '35' '36' '37' '38' '39' '40' '41' '42' '43' '44']


In [61]:
asprint(name_array)

type : <class 'numpy.ndarray'>
shape : (42,)	dimension = 1
dtype : <U22 

Array's data : 
['George Washington' 'John Adams' 'Thomas Jefferson' 'James Madison'
 'James Monroe' 'John Quincy Adams' 'Andrew Jackson' 'Martin Van Buren'
 'William Henry Harrison' 'John Tyler' 'James K. Polk' 'Zachary Taylor'
 'Millard Fillmore' 'Franklin Pierce' 'James Buchanan' 'Abraham Lincoln'
 'Andrew Johnson' 'Ulysses S. Grant' 'Rutherford B. Hayes'
 'James A. Garfield' 'Chester A. Arthur' 'Benjamin Harrison'
 'William McKinley' 'Theodore Roosevelt' 'William Howard Taft'
 'Woodrow Wilson' 'Warren G. Harding' 'Calvin Coolidge' 'Herbert Hoover'
 'Franklin D. Roosevelt' 'Harry S. Truman' 'Dwight D. Eisenhower'
 'John F. Kennedy' 'Lyndon B. Johnson' 'Richard Nixon' 'Gerald Ford'
 'Jimmy Carter' 'Ronald Reagan' 'George H. W. Bush' 'Bill Clinton'
 'George W. Bush' 'Barack Obama']


In [62]:
asprint(height_array)

type : <class 'numpy.ndarray'>
shape : (42,)	dimension = 1
dtype : int64 

Array's data : 
[189 170 189 163 183 171 185 168 173 183 173 173 175 178 183 193 178 173
 174 183 183 168 170 178 182 180 183 178 182 188 175 179 183 193 182 183
 177 185 188 188 182 185]


#### 5. NumPy 집계 함수를 이용한 탐색적 데이터 분석

In [63]:
print(f'최소 신장 : {height_array.min():5} cm')
print(f'최고 신장 : {height_array.max():5} cm\n')

print(f'평균 신장 : {height_array.mean():7.2f} cm')
print(f'분     산 : {height_array.var():7.2f} cm')
print(f'표준 편차 : {height_array.std():7.2f} cm\n')

print(f'1사분위수 : {np.percentile(height_array, 25):5} cm')
print(f'2사분위수 : {np.percentile(height_array, 50):5} cm')
print(f'중 앙 값  : {np.median(height_array):5} cm')
print(f'3사분위수 : {np.percentile(height_array, 75):5} cm\n')

최소 신장 :   163 cm
최고 신장 :   193 cm

평균 신장 :  179.74 cm
분     산 :   48.05 cm
표준 편차 :    6.93 cm

1사분위수 : 174.25 cm
2사분위수 : 182.0 cm
중 앙 값  : 182.0 cm
3사분위수 : 183.0 cm



In [64]:
print(f'최소 신장 대통령 : {height_array.min()} cm ( \
        {order_array[height_array.argmin()]} \
        {name_array[height_array.argmin()]} )')
print(f'최고 신장 대통령 : {height_array.max()} cm ( \
        {order_array[height_array.argmax()]} \
        {name_array[height_array.argmax()]} )')

최소 신장 대통령 : 163 cm (         4         James Madison )
최고 신장 대통령 : 193 cm (         16         Abraham Lincoln )


#### 여러 명의 최소/최대 신장 대통령 정보 확인

In [65]:
def select_min_height(height_array):
    ret_value = []
    min_height = height_array.min()

    # tolist() : NumPy 배열을 파이썬 list로 변환하는 method
    for i, v in enumerate(height_array.tolist()):
        if min_height == v:
            ret_value.append(i)
    return tuple(ret_value)



def select_max_height(height_array):
    ret_value = []
    max_height = height_array.max()

    for i, v in enumerate(height_array.tolist()):
        if max_height == v:
            ret_value.append(i)
    return tuple(ret_value)

In [66]:
for i in select_min_height(height_array):
    print(f'최소 신장 대통령 : {height_array.min()} cm ( \
        {order_array[i]} \
        {name_array[i]} )')
print()
    
for i in select_max_height(height_array):
    print(f'최고 신장 대통령 : {height_array.max()} cm ( \
        {order_array[i]} \
        {name_array[i]} )')

최소 신장 대통령 : 163 cm (         4         James Madison )

최고 신장 대통령 : 193 cm (         16         Abraham Lincoln )
최고 신장 대통령 : 193 cm (         36         Lyndon B. Johnson )


# Pandas

In [67]:
!pip list

Package                       Version
----------------------------- --------------
absl-py                       0.12.0
alabaster                     0.7.12
albumentations                0.1.12
altair                        4.1.0
appdirs                       1.4.4
argcomplete                   1.12.3
argon2-cffi                   20.1.0
arviz                         0.11.2
astor                         0.8.1
astropy                       4.3.1
astunparse                    1.6.3
atari-py                      0.2.9
atomicwrites                  1.4.0
attrs                         21.2.0
audioread                     2.1.9
autograd                      1.3
Babel                         2.9.1
backcall                      0.2.0
beautifulsoup4                4.6.3
bleach                        4.0.0
blis                          0.4.1
bokeh                         2.3.3
Bottleneck                    1.3.2
branca                        0.4.2
bs4                           0.0.1
CacheControl

In [68]:
import pandas as pd
import numpy as np      # set : pandas + numpy

dir(pd)

['BooleanDtype',
 'Categorical',
 'CategoricalDtype',
 'CategoricalIndex',
 'DataFrame',
 'DateOffset',
 'DatetimeIndex',
 'DatetimeTZDtype',
 'ExcelFile',
 'ExcelWriter',
 'Float64Index',
 'Grouper',
 'HDFStore',
 'Index',
 'IndexSlice',
 'Int16Dtype',
 'Int32Dtype',
 'Int64Dtype',
 'Int64Index',
 'Int8Dtype',
 'Interval',
 'IntervalDtype',
 'IntervalIndex',
 'MultiIndex',
 'NA',
 'NaT',
 'NamedAgg',
 'Period',
 'PeriodDtype',
 'PeriodIndex',
 'RangeIndex',
 'Series',
 'SparseDtype',
 'StringDtype',
 'Timedelta',
 'TimedeltaIndex',
 'Timestamp',
 'UInt16Dtype',
 'UInt32Dtype',
 'UInt64Dtype',
 'UInt64Index',
 'UInt8Dtype',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__docformat__',
 '__file__',
 '__getattr__',
 '__git_version__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_config',
 '_hashtable',
 '_is_numpy_dev',
 '_lib',
 '_libs',
 '_np_version_under1p16',
 '_np_version_under1p17',
 '_np_version_under1p18',
 '_testing',
 '_tslib',
 '_ty